name: Auto Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'breaking:')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        id: version
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if echo "$COMMIT_MSG" | grep -E "breaking:" > /dev/null; then
            BUMP_TYPE="major"
          elif echo "$COMMIT_MSG" | grep -E "feat:" > /dev/null; then
            BUMP_TYPE="minor"
          else
            BUMP_TYPE="patch"
          fi

          NEW_VERSION=$(npm version $BUMP_TYPE --no-git-tag-version)
          echo "new-version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Build and publish
        run: |
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new-version }}
          release_name: Release ${{ steps.version.outputs.new-version }}
          body: |
            ## Changes in this release:

            $(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 2>/dev/null || echo "HEAD~10")..HEAD | grep -v "Merge\|chore\|docs" || echo "- General improvements")

            ## Installation

            ```bash
            npm install @mehdiraized/dates@${{ steps.version.outputs.new-version }}
            ```

            ## Documentation

            Visit our [documentation](https://mehdiraized.github.io/dates) for more information.
          draft: false
          prerelease: false

      - name: Push changes
        run: |
          git add .
          git commit -m "chore: bump version to ${{ steps.version.outputs.new-version }}"
          git push origin main
          git tag ${{ steps.version.outputs.new-version }}
          git push origin ${{ steps.version.outputs.new-version }}

  deploy:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: mehdiraized.github.io
